### ISSUE TITLE
Update help for Search

### ISSUE THREAD

**Issue by koppor** [JabRef/help.jabref.org#89] opened 2016-09-23 07:33 UTC
Refs https://github.com/JabRef/jabref/pull/1876

> Added two new pseudo-fields for search: `anykeyword` to search for a specific keyword and `anyfield` to search in all fields (useful in combination with search in specific fields)

**Comment by mlep** [comment] 2016-09-30 09:54
Duplicate of PR https://github.com/JabRef/help.jabref.org/issues/62

**Closed by mlep** 2016-09-30 09:54 UTC
